spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgre
    password: bestuser
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/marketplace
keycloak:
  auth-server-url: http://localhost:8080   # URL вашего Keycloak
  realm: marketplace                        # имя Realm
  admin:
    client-id: admin-client   # клиент для управления пользователями
    client-secret: 0E9eZWyvUG9vzqgOeQzXO4mPIeGIQNGs  # скопируйте из Credentials этого клиента
  app:
    client-id: marketplace-backend          # клиент для входа пользователей
server:
  port: 8081